### ISSUE TITLE
Bug: Anonymous `const` items (`const _`) generate invalid Lean identifiers

### ISSUE THREAD

**Issue by ojeda** [AeneasVerif/aeneas#1250]
An anonymous `const` item:

```rust
const _: () = ();
```

translates successfully, but the Lean backend emits:

```lean4
@[global_simps, irreducible] def _ : Unit := ()
```

which Lean 4.31.0 rejects with:

```txt
Code/Funs.lean:20:32: error: unexpected token '_'; expected identifier
```

This affects e.g. anonymous compile-time assertions.

This is distinct from #1140 (which was about having a loop inside) and may be related to #1163/#1169 (they are about Rust identifiers, and perhaps the PR could cover `_` as well -- Cc: @oliver-butterley).

**Versions**:
- Aeneas: daa85d7e8940 (i.e. latest as of the time of submission)
- Charon: 0.1.232

**Comment by oliver-butterley** [comment]
`def «_» : Unit := ()` is perfectly valid Lean (as is `def myNamespace._ : Unit := ()` if that is ever relevant) so, as suggested, it appears the solution is exactly the same as needs to be done for reserved lean keywords (#1163): if the keyword appears as a identifier emitted by Aeneas but is in the Lean file as a larger name separated with dots then nothing needs to be done, if it appears alone then enclose it in french quotes.

**Comment by oliver-butterley** [comment]
PR #1163 is a bit delayed because I wanted to make it so that the list of lean keywords are automatically generated from Lean (and also because I'm slow with everything). I just checked and the prototype Lean script I have which harvests all current key words automatically produces a list which includes "_" so the one solution would naturally solve both these issues. (We are missing 172 lean/mathlib keywords in the current hand-created list 😱 although most are very unlikely to appear in Rust.)

**Comment by ia0** [comment]
This issue is different from #1163 and won't have exactly the same solution, because `_` is not an identifier in Rust (as in Lean). The following is a valid Rust program (there's no "redefining of an identifier"):

```rust
const _: () = ();
const _: () = ();
```

So the name generated by Aeneas in Lean for `_`  should not be in the image of names generated by Aeneas for identifiers.

Note that in Rust there are multiple namespaces where identifiers do not conflict: 

```rust
enum foo {}
fn foo() {}
macro_rules! foo { () => (); }
```

Maybe this is already supported (not on a computer to check), just mentioning.

**Comment by oliver-butterley** [comment]
Indeed, not exactly the same problem, @ia0 raises a good point. However I think the proposed solution does solve both. Already the identifier choosing system of Aeneas will detect duplicate identifiers and add a numerical suffix. With the current Aeneas code, the above example,
```rust
const _: () = ();
const _: () = ();
```
gets translated to 
```lean
@[global_simps, irreducible] def _ : Unit := ()
@[global_simps, irreducible] def __1 : Unit := ()
```

Consequently simply detecting when escaping in Lean is required and doing that would make them all valid and unique identifiers.

On the other hand, I see it is a bit ugly that the naming system completely ignores the distinction in Rust between identifiers and anonymous. Perhaps something generally better can be done.

**Comment by ia0** [comment]
Good point, indeed with non-deterministic generation (where the Lean name is not a function of the Rust name) it is possible to ignore [namespaces](https://doc.rust-lang.org/reference/names/namespaces.html) and anonymous items. What matters is only to generate distinct Lean names.

**Comment by oliver-butterley** [comment]
I added a regression test for exactly this in PR #1169 (`tests/src/issue-1250-anonymous-const.rs` and the corresponding Lean file).
